# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: sudo apt install -y ttfautohint
    - run: npm ci
    - run: npm run build -- ttf::SS04
    - name: Patch fonts
      run: sudo apt install -y fontforge
    - run: git clone -depth=1 git@github.com:ryanoasis/nerd-fonts.git
    - run: mv dist nerd-fonts/src/unpatched-fonts
    - run: nerd-fonts/bin/scripts/gotta-patch-em-all-font-patcher\!.sh /dist/SS04/TTF
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        # Artifact name
        name: ttf
        # A file, directory or wildcard pattern that describes what to upload
        path: nerd-fonts/patched-fonts/dist
        
              
        
